### ISSUE TITLE
Not able to get a full RxKotlinFX RxKotlin tornadofx stack working 

### ISSUE THREAD

**Issue by favetelinguis** [thomasnield/RxKotlinFX#16]
I am not able to get a stack of RxKotinFX RxKotlin and TornadoFX working due to dependecy issues, please see the following [SO post]( https://stackoverflow.com/questions/47187808/kotlin-with-rxkotlinfx-stack-gives-cannot-access-class-error)

It would be nice to have some comments in the docs or an example project showing how to get this working since it is such a common stack. In the example right now it just says x.y.z for versions witch is not helpful.

**Comment by thomasnield** [comment]
@favetelinguis I usually recommend explicitly setting the latest RxJava2 as a dependency as you just did, just because it's hard to make new releases for every dependency update. 

So you're good now?

**Comment by favetelinguis** [comment]
Yes im good. I switched to gradle ten i dont need the explicit dependency.
Thanks for the reply.

Den 13 nov 2017 15:30 skrev "Thomas Nield" <notifications@github.com>:
