### ISSUE TITLE
BindingList

### ISSUE THREAD

**Issue by raniejade** [thomasnield/RxKotlinFX#6]
It would be nice to have something similar to RxJava's internal API `rx.internal.SubscriptionList`.

``` kotlin
class BindingList {
    fun add(binding: binding) { ... }
    fun dispose() {
        ...
        bindings.each { it.dispose() }
        ...
    }

    fun invalidate() {
        ...
        bindings.each { it.invalidate() }
        ...
    }

    fun isValid() { ... }
}
```

``` kotlin
val bindings = BindingList()
bindings.add(...)
bindings.add(...)
bindings.add(...)

// later on
bindings.dispose()
```

**Comment by thomasnield** [comment]
I've thought about this before. Usually I would make a `List<Binding>` and use that,  but I guess it would be nice to have a `Binding` equivalent to `CompositeSubscription`. 

I'll add this to RxJavaFX later which will put it here as well.

**Comment by thomasnield** [comment]
@raniejade please see my first implementation in [RxJavaFX here](https://github.com/ReactiveX/RxJavaFX/issues/23). If you like it I will port it over here with Kotlin extension methods.

**Comment by thomasnield** [comment]
I'm thinking of not only adding `plusAssign()` operator overload, but maybe an optional argument for `toBinding()` that accepts a `CompositeBinding` it will add itself to. What do you think? 

``` kotlin
val source1: Observable<Int> = ...
val source2: Observable<Int> = ...
val source3: Observable<Int> = ...

val bindings = CompositeBinding()

//option 1
val binding1= source1.toBinding()
bindings += binding1

//option 2
source2.toBinding().apply { 
    bindings += this
}

//option 3
source3.toBinding(bindings)
```

**Comment by raniejade** [comment]
I think option 1 and 2 will catch most of the use case. Option 3 looks weird to me, but it's up to you.

This might be an overkill but probably you can add something like this.

``` kotlin

class CompositeBindingBuilder {
    val bindings = CompositeBinding()

    operator fun CompositeBinding.unaryPlus() {
        bindings.add(this)
    }
}
object CompositeBindings {
    fun create(block: CompositeBindingBuilder.() -> Unit): CompositeBinding {
        return CompositeBindingBuilder().let {
            block.invoke(this)
            this.bindings // or just bindings
        }
    }
}
```

Then you can do something like this:

``` kotlin
val bindings = CompositeBindings.create {
    + binding1
    + binding2
}
```

**Comment by thomasnield** [comment]
I'll leave out #3 as I wasn't a big fan of it anyway. That is a very interesting proposal though with the builder. Reminds me of patterns in the TornadoFX project. Let me think about that tomorrow and I may ask @edvin for his opinion.

**Comment by edvin** [comment]
I won't pretend to understand everything here, but an alternative to option 3 would be:

``` kotlin
source3.toBinding().addTo(bindings)
```

`CompositeBindings` could possibly take a list of varargs parameter of bindings as well:

``` kotlin
val bindings = CompositeBindings(binding1, binding2)
```

You could even support converting observables to bindings in that constructor as well:

``` kotlin
val bindings = CompositeBindings(source1, source2)
```

Don't know if any of this makes sense though :)

**Comment by thomasnield** [comment]
Actually the first two kinda do make sense. The third loses access to the individual Binding instances unless you use apply() with them. But I kind of like the first one as am alternative to the builder. What do you think @raniejade? 

Thanks @edvin!

**Comment by raniejade** [comment]
Option 1 looks good, as long as `addTo(...)` returns the binding.

``` kotlin
val binding = source3.toBinding().addTo(bindings)
```

**Comment by thomasnield** [comment]
Agreed. I'll implement this today.

**Comment by thomasnield** [comment]
Okay drafting a release. Here are the extensions for `CompositeBinding`. 

``` kotlin

/**
 * Add this `Binding` to the provided `CompositeBinding`, and returns itself
 * @return `Binding`
 */
fun <T> Binding<T>.addto(compositeBinding: CompositeBinding): Binding<T> {
    compositeBinding.add(this)
    return this
}

operator fun <T> CompositeBinding.plusAssign(binding: Binding<T>) = add(binding)

operator fun CompositeBinding.plusAssign(compositeBinding: CompositeBinding) = add(compositeBinding)

operator fun <T> CompositeBinding.minusAssign(binding: Binding<T>) = remove(binding)

operator fun CompositeBinding.minusAssign(compositeBinding: CompositeBinding) = remove(compositeBinding)
```
