### ISSUE TITLE
Some helpful patterns I'm using.

### ISSUE THREAD

**Issue by radicaled** [thomasnield/RxKotlinFX#7]
Didn't want to hijack https://github.com/edvin/tornadofx/issues/120, so demonstrating to some of the patterns I'm using in my codebase.

I'm currently in the middle of a large refactoring, so this code might have some super obvious bugs. It worked before, honest!

RxProperty.kt:

``` kotlin

class RxProperty<T>(initialValue: T) {
    val observable: Observable<T>
    private var propertyField: T = initialValue
    private val subject = BehaviorSubject.create<T>(propertyField)

    companion object {
        /**
         * Two way binding between two RxProperty objects.
         * It relies on Observable.distinctUntilChanged() to prevent
         * infinite loops.
         */
        fun <T> bind(property1: RxProperty<T>, property2: RxProperty<T>) {
            property1.bindTo(property2)
            property2.bindTo(property1)
        }
    }

    init {
        propertyField = initialValue
        observable = subject.distinctUntilChanged()
    }

    // TODO: followed javafx here -- should have just done "value =" get/set for better interop
    fun get(): T = propertyField
    fun set(value: T): RxProperty<T> {
        propertyField = value
        subject.onNext(value)
        return this
    }
    // TODO: Both of these were a mistake: should have just done asObservable or toObservable
    fun observeOn(scheduler: Scheduler) = observable.observeOn(scheduler)
    fun subscribe(callback: (value: T) -> Unit) = observable.subscribe(callback)

    /**
     * Create a one way binding from this object to another RxProperty
     */
    fun bindTo(receiver: RxProperty<T>): Subscription {
        return subscribe { receiver.set(it) }
    }
```

RxProxy, a helper delegate for RxProperty:

``` kotlin
/**
 * Maps a field to an RxProperty, so that it can be used like a getter/setter bean.
 *
 * Example:
 *  class Demo {
 *      val textProperty = RxProperty("default text")
 *      val text by RxProxy(textProperty)
 *
 *      fun test() {
 *        text = "One, two, three!"
 *      }
 *  }
 */
class RxProxy<T>(val rxProperty: RxProperty<T>) {
    operator fun getValue(thisRef: Any?, property: KProperty<*>) = rxProperty.get()


    operator fun setValue(thisRef: Any?, property: KProperty<*>, value: T) {
        rxProperty.set(value)
    }
}
```

Disposables:

``` kotlin
interface DisposableResource {
    fun dispose()
}

/**
 * Lifecycle object that unsubscribes all its subscriptions when disposed
 */
class RxDisposable : DisposableResource {
    val subscriptions = CompositeSubscription()

    fun addSusbcription(subscription: Subscription) {
        subscriptions.add(subscription)
    }

    override fun dispose() {
        subscriptions.unsubscribe()
    }
}
```

disposeWith

``` kotlin
fun Subscription.disposeWith(instance: RxDisposable) {
    instance.addSusbcription(this)
}
```

Misc?

``` kotlin
fun <R, T : R> Observable<T>.bindTo(property: RxProperty<R>): Subscription {
    return subscribe { property.set(it) }
}

fun <T> Observer<T>.bindTo(observer: Observable<T>): Subscription {
    return observer.subscribe(this)
}
```

I haven't upgraded my copy of RxKotlinFX in a while, so some of these patterns might already exist or have a better solution. The `disposeWith` pattern came from RxSwift, where they have "DisposeBags" that handle disposing subscriptions automatically. I've generalized it to `ResourceDisposable` so I can dispose of other, non-Rx resources when necessary.

**Comment by thomasnield** [comment]
Give me a day or two to go through this. At first glance I may have implemented a lot of this with `BindingSubscriber`, `CompositeBinding`, and a few extension functions to utilize those utilities. But I'll see if you are trying to accomplish anything that we may have missed. 

@raniejade I invited @radicaled to share any patterns he was using just to make sure we captured them all. Feel free to provide any input, but I think we got all of these. Correct?

**Comment by raniejade** [comment]
Most patterns here are already implemented by TorndadoFX. The demo for `RxProxy` looks weird, `val` should be immutable right? Or do you mean `var` perhaps? Got mixed feelings for `RxProxy`, lessens boilerplate but introduces some runtime overhead. 

One pattern I can think of is lazy JavaFX properties. I see a lot of this in JavaFX control classes.

``` kotlin
private var _textProperty: StringProperty?
fun textProperty(): StringProperty {
    if (_textProperty == null) {
        _textProperty = SimpleStringProperty(this, "text")
    }
    return _textProperty
}
var text: String
    get() {
        if (_textProperty == null) {
            return SOME_DEFAULT_VALUE
        }
        return textProperty().get()
    }
    set(value) {
        textProperty().set(value)
    }
```

This minimize the runtime memory footprint of your object, the property will only be instantiated if you access the property or set a value for the first time.

**Comment by radicaled** [comment]
> The demo for RxProxy looks weird, val should be immutable right? Or do you mean var perhaps?

Var, yeah. No code analysis in comments. :)

I haven't really measured the overhead of the RxProxy delegate vs writing the getter/setter by hand, so I can't really comment on if that's the best way to handle the boilerplate.

Lazy loading is interesting -- I didn't implement it because I wanted field-like access, but I can see how it does make for better memory usage for a framework.

**Comment by thomasnield** [comment]
I think Kotlin already comes with lazy property delegates.

```
val myExpensiveItem: MyItem by lazy { buildExpensiveItem() }
```

This isn't made specifically for JavaFX though, but I think it could accomplish the same thing...

**Comment by raniejade** [comment]
I'm aware of that however, in the pattern the first read to the property value won't instantiate the property but will return a default value.

``` kotlin
    get() {
        if (_textProperty == null) {
            return SOME_DEFAULT_VALUE
        }
        return textProperty().get()
    }
```

With `lazy` the null check is not possible.

**Comment by thomasnield** [comment]
Okay I see. But @edvin doesn't TornadoFX have a delegate already for properties? And if this lazy functionality isn't present already maybe it should be there?

**Comment by edvin** [comment]
Yes, TornadoFX has property delegates, but they are not lazy. I think that might be possible, but it would complicate certain aspects of how they are implemented right now. I'll have a look to check if it would be possible to make it lazy though :)

**Comment by thomasnield** [comment]
Okay, that's what I thought. I think it would be safe to say if we did decide to pursue that, it would belong in TornadoFX and not RxKotlinFX, because it doesn't have anything to do with RxJava.

**Comment by thomasnield** [comment]
I'm going to go ahead and close this. @radicaled if you want to continue this at some point,  go ahead and file the issue on TornadoFX. @edvin and I will investigate this further after that.
